[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx vite build && npx esbuild server/index.prod.ts --platform=node --bundle --format=esm --outdir=dist --external:pg --external:drizzle-orm --external:express --external:socket.io --external:ws"

[deploy]
startCommand = "node dist/index.prod.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
